# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:06:24+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, constr


class ApplicationState(Enum):
    CREATING = 'CREATING'
    DELETING = 'DELETING'
    ACTIVE = 'ACTIVE'
    CREATE_FAILED = 'CREATE_FAILED'
    DELETE_FAILED = 'DELETE_FAILED'


class Arn(RootModel[constr(pattern=r'^arn:[!-~]+$', min_length=1, max_length=1600)]):
    root: constr(pattern=r'^arn:[!-~]+$', min_length=1, max_length=1600)


class ClientRequestToken(
    RootModel[constr(pattern=r'^[a-zA-Z0-9-_]+$', min_length=1, max_length=64)]
):
    root: constr(pattern=r'^[a-zA-Z0-9-_]+$', min_length=1, max_length=64)


class ConflictException(RootModel[Any]):
    root: Any


class DeleteApplicationRequest(BaseModel):
    pass


class DeleteApplicationResponse(BaseModel):
    pass


class DescribeApplicationRequest(BaseModel):
    pass


class Description(
    RootModel[constr(pattern=r'^[ -~]*$', min_length=1, max_length=2048)]
):
    root: constr(pattern=r'^[ -~]*$', min_length=1, max_length=2048)


class ErrorMessage(RootModel[str]):
    root: str


class Id(
    RootModel[
        constr(
            pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
            min_length=36,
            max_length=36,
        )
    ]
):
    root: constr(
        pattern=r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$',
        min_length=36,
        max_length=36,
    )


class InternalFailureException(RootModel[Any]):
    root: Any


class InvalidRequestException(RootModel[Any]):
    root: Any


class LimitExceededException(RootModel[Any]):
    root: Any


class ListApplicationsRequest(BaseModel):
    pass


class ListTagsForResourceRequest(BaseModel):
    pass


class Name(RootModel[constr(pattern=r'^[ -~]*$', min_length=1, max_length=100)]):
    root: constr(pattern=r'^[ -~]*$', min_length=1, max_length=100)


class NextToken(
    RootModel[constr(pattern=r'^[A-Za-z0-9+/=]+$', min_length=1, max_length=2048)]
):
    root: constr(pattern=r'^[A-Za-z0-9+/=]+$', min_length=1, max_length=2048)


class ResourceArn(RootModel[str]):
    root: str


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class SsoClientId(RootModel[str]):
    root: str


class TagKey(
    RootModel[
        constr(pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=1, max_length=128)
    ]
):
    root: constr(
        pattern=r'^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$', min_length=1, max_length=128
    )


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey]


class TagResourceResponse(BaseModel):
    pass


class TagValue(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class ThrottlingException(RootModel[Any]):
    root: Any


class Timestamp(RootModel[int]):
    root: int


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class UpdateApplicationRequest(BaseModel):
    applicationDescription: Optional[Description] = None
    applicationName: Optional[Name] = None
    clientToken: Optional[ClientRequestToken] = None


class UpdateApplicationResponse(BaseModel):
    pass


class Url(RootModel[constr(pattern=r'^https\://\S+$', min_length=1, max_length=256)]):
    root: constr(pattern=r'^https\://\S+$', min_length=1, max_length=256)


class ApplicationsPostRequest(BaseModel):
    applicationDescription: Optional[
        constr(pattern=r'^[ -~]*$', min_length=1, max_length=2048)
    ] = Field(None, description='An optional description of the web application.')
    applicationName: constr(pattern=r'^[ -~]*$', min_length=1, max_length=100) = Field(
        ..., description='The name of the web application.'
    )
    clientToken: Optional[
        constr(pattern=r'^[a-zA-Z0-9-_]+$', min_length=1, max_length=64)
    ] = Field(
        None,
        description="A unique case-sensitive identifier that you can provide to ensure the idempotency of the request. Don't reuse this client token if a new idempotent request is required.",
    )
    roleArn: constr(pattern=r'^arn:[!-~]+$', min_length=1, max_length=1600) = Field(
        ...,
        description='<p>The ARN of the role that the web application assumes when it interacts with AWS IoT Core.</p> <note> <p>The name of the role must be in the form <code>AWSIotFleetHub_<i>random_string</i> </code>.</p> </note>',
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='A set of key/value pairs that you can use to manage the web application resource.',
    )


class ApplicationsApplicationIdPatchRequest(BaseModel):
    applicationDescription: Optional[
        constr(pattern=r'^[ -~]*$', min_length=1, max_length=2048)
    ] = Field(None, description='An optional description of the web application.')
    applicationName: Optional[
        constr(pattern=r'^[ -~]*$', min_length=1, max_length=100)
    ] = Field(None, description='The name of the web application.')
    clientToken: Optional[
        constr(pattern=r'^[a-zA-Z0-9-_]+$', min_length=1, max_length=64)
    ] = Field(
        None,
        description="A unique case-sensitive identifier that you can provide to ensure the idempotency of the request. Don't reuse this client token if a new idempotent request is required.",
    )


class TagsResourceArnPostRequest(BaseModel):
    tags: Dict[str, TagValue] = Field(
        ..., description='The new or modified tags for the resource.'
    )


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey]


class ApplicationSummary(BaseModel):
    applicationCreationDate: Optional[Timestamp] = None
    applicationDescription: Optional[Description] = None
    applicationId: Id
    applicationLastUpdateDate: Optional[Timestamp] = None
    applicationName: Name
    applicationState: Optional[ApplicationState] = None
    applicationUrl: Url


class CreateApplicationResponse(BaseModel):
    applicationArn: Arn
    applicationId: Id


class TagMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class TagResourceRequest(BaseModel):
    tags: TagMap


class ApplicationSummaries(RootModel[List[ApplicationSummary]]):
    root: List[ApplicationSummary]


class CreateApplicationRequest(BaseModel):
    applicationDescription: Optional[Description] = None
    applicationName: Name
    clientToken: Optional[ClientRequestToken] = None
    roleArn: Arn
    tags: Optional[TagMap] = None


class DescribeApplicationResponse(BaseModel):
    applicationArn: Arn
    applicationCreationDate: Timestamp
    applicationDescription: Optional[Description] = None
    applicationId: Id
    applicationLastUpdateDate: Timestamp
    applicationName: Name
    applicationState: ApplicationState
    applicationUrl: Url
    errorMessage: Optional[ErrorMessage] = None
    roleArn: Arn
    ssoClientId: Optional[SsoClientId] = None
    tags: Optional[TagMap] = None


class ListApplicationsResponse(BaseModel):
    applicationSummaries: Optional[ApplicationSummaries] = None
    nextToken: Optional[NextToken] = None


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[TagMap] = None
